# Generated by Django 4.1.1 on 2022-09-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('status', models.CharField(default='Active', max_length=10, verbose_name='status')),
                ('suspension_expires', models.DateField(verbose_name='suspensions_expires')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
