# Generated by Django 4.1.1 on 2022-09-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airportmgt', '0004_alter_appuser_suspension_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='failed_login_tries',
            field=models.IntegerField(default=0),
        ),
    ]
