# Generated by Django 4.1.1 on 2022-09-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airportmgt', '0005_appuser_failed_login_tries'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedMac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=32, verbose_name='mac_address')),
                ('attack_date', models.DateTimeField(verbose_name='attack_date')),
                ('date_banned', models.DateTimeField(verbose_name='date_banned')),
            ],
        ),
    ]
