# Generated by Django 4.1.1 on 2022-09-18 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airportmgt', '0006_bannedmac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannedmac',
            name='attack_date',
        ),
        migrations.RemoveField(
            model_name='bannedmac',
            name='date_banned',
        ),
        migrations.AddField(
            model_name='bannedmac',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannedmac',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
    ]
